// The story, in order. Each photo can get a time ("HH:MM") once we have it,
// the site then shows it plus how long before/after Dekel was born.
const BIRTH_TIME = "16:08";

const STORY = [
  {
    title: "מחכים לך",
    text: "החדר עוד שקט, הידיים שלובות, והלב כבר יודע שהיום זה היום.",
    photos: [
      { file: "_DSC8480A.jpg", time: null },
      { file: "_DSC8495A.jpg", time: null },
      { file: "_DSC8498A.jpg", time: null },
      { file: "_DSC8513A.jpg", time: null },
      { file: "_DSC8527A.jpg", time: null },
      { file: "_DSC8535A.jpg", time: null },
      { file: "_DSC8536A.jpg", time: null },
      { file: "_DSC8541A.jpg", time: null },
      { file: "_DSC8564A.jpg", time: null },
    ],
  },
  {
    title: "הגלים",
    text: "גל אחרי גל, נשימה אחרי נשימה. יד ביד, עד הסוף.",
    photos: [
      { file: "_DSC8634A.jpg", time: null },
      { file: "_DSC8639A.jpg", time: null },
      { file: "_DSC8649A.jpg", time: null },
      { file: "_DSC8668A.jpg", time: null },
      { file: "_DSC8672A.jpg", time: null },
      { file: "_DSC8676.jpg", time: null },
      { file: "_DSC8679A.jpg", time: null },
      { file: "_DSC8684A.jpg", time: null },
      { file: "_DSC8685A.jpg", time: null },
      { file: "_DSC8734A.jpg", time: null },
      { file: "_DSC8744A.jpg", time: null },
      { file: "_DSC8756A.jpg", time: null },
    ],
  },
  { birth: true, title: "דקל נולד", text: "ובשנייה אחת, העולם התחיל מחדש." },
  {
    title: "שלום, דקל",
    text: "בכי ראשון, עור על עור, ודמעות של אבא.",
    photos: [
      { file: "_DSC8805A.jpg", time: null },
      { file: "_DSC8808A.jpg", time: null },
      { file: "_DSC8816A.jpg", time: null },
      { file: "_DSC8817A.jpg", time: null },
      { file: "_DSC8820A.jpg", time: null },
      { file: "_DSC8823A.jpg", time: null },
      { file: "_DSC8825A.jpg", time: null },
      { file: "_DSC8833A.jpg", time: null },
      { file: "_DSC8835A.jpg", time: null },
      { file: "_DSC8839A.jpg", time: null },
      { file: "_DSC8841A.jpg", time: null },
      { file: "_DSC8842A.jpg", time: null },
      { file: "_DSC8853A.jpg", time: null },
      { file: "_DSC8872A.jpg", time: null },
      { file: "_DSC8887A.jpg", time: null },
    ],
  },
  {
    title: "הראשונים",
    text: "שקילה ראשונה, כובע ראשון, חיבוק ראשון. 3.590 ק״ג של מתיקות.",
    photos: [
      { file: "_DSC8895A.jpg", time: null },
      { file: "_DSC8904A.jpg", time: null },
      { file: "_DSC8918A.jpg", time: null },
      { file: "_DSC8922A.jpg", time: null },
      { file: "_DSC8925A.jpg", time: null },
      { file: "_DSC8937A.jpg", time: null },
      { file: "_DSC8966A.jpg", time: null },
      { file: "_DSC8970A.jpg", time: null },
      { file: "_DSC8977A.jpg", time: null },
      { file: "_DSC8983A.jpg", time: null },
      { file: "_DSC8988A.jpg", time: null },
      { file: "_DSC8997A.jpg", time: null },
    ],
  },
  {
    title: "משפחה",
    text: "הידיים של אבא, הלב של אמא, ומקום חדש וקטן שכבר מרגיש כמו בית.",
    photos: [
      { file: "_DSC9021A.jpg", time: null },
      { file: "_DSC9046A.jpg", time: null },
      { file: "_DSC9058A.jpg", time: null },
      { file: "_DSC9064A.jpg", time: null },
      { file: "_DSC9068A.jpg", time: null },
      { file: "_DSC9083A.jpg", time: null },
      { file: "_DSC9087A.jpg", time: null },
      { file: "_DSC9091A.jpg", time: null },
      { file: "_DSC9101A.jpg", time: null },
      { file: "_DSC9108A.jpg", time: null },
      { file: "_DSC9115A.jpg", time: null },
      { file: "_DSC9119A.jpg", time: null },
    ],
  },
];
